baseURL = 'https://blog.arwalk.net/'
languageCode = 'en-us'
title = "Arwalk's blog"
theme = "pickles"

[author]
    name = "Arwalk"

[markup]
  [markup.asciidocExt]
    extensions = []
    [markup.asciidocExt.attributes]
      source-highlighter="rouge"
      relfileprefix="../"
      relfilesuffix="/"

[params]
  paginate = 10
  custom_css = ["css/monokai.css"]
  github = "Arwalk"
  youtube = "Arwalk"
  bio = "I pretend every day that i'm a software engineer and have been very successful at it."
  subtitle = "Programming, video games, stuff."
  contact = "mailto:siragentprovocateurarwalk@gmail.com"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Mastodon"
    url = "https://noagendasocial.com/@Arwalk"
    weight = 1

[security]
    enableInlineShortcodes = false

[security.exec]
    allow = ["^dart-sass-embedded$", "^go$", "^npx$", "^postcss$", "^asciidoctor$"]
    osEnv = ["(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM|RUBYLIB)$"]

[security.funcs]
    getenv = ["^HUGO_"]

[security.http]
    methods = ["(?i)GET|POST"]
    urls = [".*"]