baseURL = 'https://blog.arwalk.net/'
languageCode = 'en-us'
title = "Arwalk's blog"
theme = "pickles"
[markup]
  [markup.asciidocExt]
    extensions = []
    [markup.asciidocExt.attributes]
    source-highlighter="rouge"
[params]
  custom_css = ["css/molokai.css"]